### ISSUE TITLE
Identify which controls need to be implemented within the EF-CMS

### ISSUE THREAD

**Issue by waldoj** [ustaxcourt/ato#16]
Many controls must be implemented at an organizational level (e.g. the creation of new policies) but do not create any requirements for the EF-CMS. (The policies may, in turn, create requirements, but the controls themselves do not.) Identify which controls require implementation within the EF-CMS, or that are based on the contents / structure of the EF-CMS.

**Comment by waldoj** [comment]
I count 99 controls that need to be implemented within the EF-CMS, and 7 that I'm unclear on. I will provide a list here shortly.

**Comment by waldoj** [comment]
| Control | Automatable |
| ------- | ----------- |
| AC-1 | no |
| AC-4 | yes |
| AC-5 | yes |
| AC-6 | no |
| AC-8 | yes |
| AC-9 | yes |
| AC-23 | unclear |
| AC-25 | yes |
| AU-2 | yes |
| AU-3 | yes |
| AU-4 | yes |
| AU-5 | yes |
| AU-6 | yes |
| AU-8 | yes |
| AU-9 | yes |
| AU-12 | yes |
| AU-13 | yes |
| AU-14 | yes |
| AU-15 | yes |
| AU-16 | no |
| CA-1 | no |
| CA-3 | unclear |
| CM-2 | yes |
| CM-5 | yes |
| CM-6 | yes |
| CM-7 | yes |
| CM-8 | yes |
| CM-9 | no |
| CP-6 | yes |
| CP-7 | yes |
| CP-8 | no |
| CP-9 | yes |
| CP-10 | no |
| CP-11 | yes |
| CP-12 | yes |
| CP-13 | yes |
| IA-2 | unclear |
| IA-3 | no |
| IA-5 | unclear |
| IA-7 | yes |
| IA-8 | yes |
| IA-9 | yes |
| IA-10 | yes |
| IA-11 | yes |
| IR-1 | no |
| IR-4 | no |
| IR-5 | yes |
| IR-6 | no |
| IR-8 | no |
| IR-9 | no |
| IR-10 | no |
| MA-1 | no |
| MP-1 | no |
| MP-2 | no |
| MP-4 | no |
| MP-5 | no |
| MP-6 | no |
| MP-7 | no |
| MP-8 | yes |
| PE-1 | no |
| PE-2 | no |
| PE-3 | no |
| PE-4 | no |
| PE-6 | no |
| PE-9 | no |
| PE-10 | no |
| PE-11 | no |
| PE-12 | no |
| PE-13 | no |
| PE-14 | no |
| PE-15 | no |
| PE-19 | no |
| PE-20 | no |
| PL-1 | no |
| PL-2 | no |
| PL-7 | no |
| PL-8 | yes |
| PL-9 | no |
| PS-1 | no |
| PS-2 | no |
| PS-3 | no |
| PS-4 | no |
| PS-7 | no |
| RA-1 | no |
| RA-2 | no |
| RA-3 | no |
| RA-5 | yes |
| RA-6 | no |
| SA-1 | no |
| SA-2 | no |
| SA-3 | no |
| SA-4 | no |
| SA-8 | no |
| SA-9 | no |
| SA-10 | no |
| SA-11 | yes |
| SA-12 | no |
| SA-13 | unclear |
| SA-14 | no |
| SA-17 | unclear |
| SA-18 | yes |
| SA-19 | yes |
| SA-20 | unclear |
| SA-21 | no |
| SA-22 | yes |
| SC-1 | no |
| SC-2 | yes |
| SC-3 | yes |
| SC-4 | unclear |
| SC-5 | yes |
| SC-6 | yes |
| SC-7 | yes |
| SC-8 | unclear |
| SC-11 | yes |
| SC-12 | unclear |
| SC-13 | unclear |
| SC-15 | no |
| SC-16 | no |
| SC-17 | yes |
| SC-19 | no |
| SC-20 | yes |
| SC-21 | yes |
| SC-22 | yes |
| SC-23 | yes |
| SC-24 | yes |
| SC-25 | yes |
| SC-26 | yes |
| SC-27 | unclear |
| SC-28 | yes |
| SC-29 | no |
| SC-30 | unclear |
| SC-31 | unclear |
| SC-32 | yes |
| SC-34 | yes |
| SC-36 | yes |
| SC-37 | no |
| SC-38 | no |
| SC-39 | yes |
| SC-40 | no |
| SC-41 | no |
| SC-42 | no |
| SC-43 | no |
| SC-44 | yes |
| SI-1 | no |
| SI-2 | yes |
| SI-3 | yes |
| SI-4 | yes |
| SI-5 | no |
| SI-6 | yes |
| SI-7 | yes |
| SI-10 | yes |
| SI-13 | yes |
| SI-14 | yes |
| SI-15 | yes |
| SI-16 | yes |
| SI-17 | yes |

**Comment by softwaretzar** [comment]
Should probably include AC-10 as well

**Comment by waldoj** [comment]
Organizationally, 18F does not recommend applying SA-4 as written, because it both requires waterfall development practices and requires the development vendor to perform security work that is best performed by the agency (or another vendor of the agency's choice).

**Comment by softwaretzar** [comment]
What about reinterpreting SA-4 within the context of DevOps & CI/CD?... so changing:

(As written) "Include the following requirements, descriptions, and criteria, explicitly or by reference, in the acquisition contract for the system, system component, or system service:"

and making it something more like: 

"Include the following requirements, descriptions, and criteria, explicitly or by reference, in the backlog for the system, system component, or system service with CAT I and CAT II vulnerabilities prioritized above functional requirements"

For instance SA-4 (1) states: "Require the developer of the system, system component, or system service to provide a description of the functional properties of the controls to be implemented."

This seems to automatically fall out as part of our current process and probably already met if we reinterpret the parent control for agile.

**Comment by waldoj** [comment]
Here are all 262 controls and enhancements, classified by whether they require any kind of implementation within the EF-CMS, at least as best as I was able to determine after a quick review of each.

| # | Name | Enhancement | EF-CMS |
|  --- | ----- | ------------ | ------- |
| AC-1 | Access Control Policy and Procedures |  | no |
| AC-2 | Account Management |  | no |
| AC-2 | Account Management | 1 | yes |
| AC-2 | Account Management | 2 | yes |
| AC-2 | Account Management | 3 | yes |
| AC-2 | Account Management | 4 | yes |
| AC-3 | Access Enforcement |  | yes |
| AC-4 | Information Flow Enforcement |  | yes |
| AC-5 | Separation of Duties |  | yes |
| AC-6 | Least Privilege |  | yes |
| AC-6 | Least Privilege | 1 | yes |
| AC-6 | Least Privilege | 2 | no |
| AC-6 | Least Privilege | 5 | yes |
| AC-6 | Least Privilege | 9 | yes |
| AC-6 | Least Privilege | 10 | yes |
| AC-7 | Unsuccessful Logon Attempts |  | yes |
| AC-8 | System Use Notification |  | yes |
| AC-10 | Concurrent Session Control |  | yes |
| AC-11 | Session Lock |  | yes |
| AC-11 | Session Lock | 1 | yes |
| AC-12 | Session Termination |  | yes |
| AC-14 | Permitted Actions Without Identification or Authentication |  | yes |
| AC-17 | Remote Access |  | no |
| AC-17 | Remote Access | 1 | yes |
| AC-17 | Remote Access | 2 | yes |
| AC-17 | Remote Access | 3 | yes |
| AC-17 | Remote Access | 4 | yes |
| AC-18 | Wireless Access |  | no |
| AC-18 | Wireless Access | 1 | yes |
| AC-19 | Access Control for Mobile Devices |  | no |
| AC-19 | Access Control for Mobile Devices | 5 | no |
| AC-20 | Use of External Information Systems |  | no |
| AC-20 | Use of External Information Systems | 1 | no |
| AC-20 | Use of External Information Systems | 2 | no |
| AC-21 | Information Sharing |  | ? |
| AC-22 | Publicly Accessible Content |  | no |
| AT-1 | Security Awareness and Training Policy and Procedures |  | no |
| AT-2 | Security Awareness Training |  | no |
| AT-2 | Security Awareness Training | 2 | no |
| AT-3 | Role-based Security Training |  | no |
| AT-4 | Security Training Records |  | no |
| AU-1 | Audit and Accountability Policy and Procedures |  | no |
| AU-2 | Audit Events |  | yes |
| AU-2 | Audit Events | 3 | no |
| AU-3 | Content of Audit Records |  | yes |
| AU-3 | Content of Audit Records | 1 | yes |
| AU-4 | Audit Storage Capacity |  | yes |
| AU-5 | Response to Audit Processing Failures |  | yes |
| AU-6 | Audit Review, Analysis, and Reporting |  | yes |
| AU-6 | Audit Review, Analysis, and Reporting | 1 | yes |
| AU-6 | Audit Review, Analysis, and Reporting | 3 | yes |
| AU-7 | Audit Reduction and Report Generation |  | yes |
| AU-7 | Audit Reduction and Report Generation | 1 | yes |
| AU-8 | Time Stamps |  | yes |
| AU-8 | Time Stamps | 1 | yes |
| AU-9 | Protection of Audit Information |  | yes |
| AU-9 | Protection of Audit Information | 4 | yes |
| AU-11 | Audit Record Retention |  | yes |
| AU-12 | Audit Generation |  | yes |
| CA-1 | Security Assessment and Authorization Policy and Procedures |  | no |
| CA-2 | Security Assessments |  | no |
| CA-2 | Security Assessments | 1 | no |
| CA-3 | System Interconnections |  | no |
| CA-3 | System Interconnections | 5 | yes |
| CA-5 | Plan of Action and Milestones |  | no |
| CA-6 | Security Authorization |  | no |
| CA-7 | Continuous Monitoring |  | yes |
| CA-7 | Continuous Monitoring | 1 | no |
| CA-9 | Internal System Connections |  | yes |
| CM-1 | Configuration Management Policy and Procedures |  | no |
| CM-2 | Baseline Configuration |  | yes |
| CM-2 | Baseline Configuration | 1 | no |
| CM-2 | Baseline Configuration | 3 | yes |
| CM-2 | Baseline Configuration | 7 | no |
| CM-3 | Configuration Change Control |  | ? |
| CM-3 | Configuration Change Control | 2 | yes |
| CM-4 | Security Impact Analysis |  | no |
| CM-5 | Access Restrictions for Change |  | yes |
| CM-6 | Configuration Settings |  | yes |
| CM-7 | Least Functionality |  | yes |
| CM-7 | Least Functionality | 1 | yes |
| CM-7 | Least Functionality | 2 | yes |
| CM-7 | Least Functionality | 4 | yes |
| CM-8 | Information System Component Inventory |  | yes |
| CM-8 | Information System Component Inventory | 1 | yes |
| CM-8 | Information System Component Inventory | 3 | yes |
| CM-8 | Information System Component Inventory | 5 | no |
| CM-9 | Configuration Management Plan |  | no |
| CM-10 | Software Usage Restrictions |  | yes |
| CM-11 | User-installed Software |  | no |
| CP-1 | Contingency Planning Policy and Procedures |  | no |
| CP-2 | Contingency Plan |  | no |
| CP-2 | Contingency Plan | 1 | no |
| CP-2 | Contingency Plan | 3 | no |
| CP-2 | Contingency Plan | 8 | no |
| CP-3 | Contingency Training |  | no |
| CP-4 | Contingency Plan Testing |  | no |
| CP-4 | Contingency Plan Testing | 1 | no |
| CP-6 | Alternate Storage Site |  | yes |
| CP-6 | Alternate Storage Site | 1 | yes |
| CP-6 | Alternate Storage Site | 3 | no |
| CP-7 | Alternate Processing Site |  | yes |
| CP-7 | Alternate Processing Site | 1 | yes |
| CP-7 | Alternate Processing Site | 2 | yes |
| CP-7 | Alternate Processing Site | 3 | no |
| CP-8 | Telecommunications Services |  | no |
| CP-8 | Telecommunications Services | 1 | no |
| CP-8 | Telecommunications Services | 2 | no |
| CP-9 | Information System Backup |  | yes |
| CP-9 | Information System Backup | 1 | yes |
| CP-10 | Information System Recovery and Reconstitution |  | yes |
| CP-10 | Information System Recovery and Reconstitution | 2 | yes |
| IA-1 | Identification and Authentication Policy and Procedures |  | no |
| IA-2 | Identification and Authentication (Organizational Users) |  | yes |
| IA-2 | Identification and Authentication (Organizational Users) | 1 | yes |
| IA-2 | Identification and Authentication (Organizational Users) | 2 | yes |
| IA-2 | Identification and Authentication (Organizational Users) | 3 | yes |
| IA-2 | Identification and Authentication (Organizational Users) | 8 | yes |
| IA-2 | Identification and Authentication (Organizational Users) | 11 | yes |
| IA-2 | Identification and Authentication (Organizational Users) | 12 | yes |
| IA-3 | Device Identification and Authentication |  | no |
| IA-4 | Identifier Management |  | no |
| IA-5 | Authenticator Management |  | yes |
| IA-5 | Authenticator Management | 1 | yes |
| IA-5 | Authenticator Management | 2 | yes |
| IA-5 | Authenticator Management | 3 | no |
| IA-5 | Authenticator Management | 11 | yes |
| IA-6 | Authenticator Feedback |  | yes |
| IA-7 | Cryptographic Module Authentication |  | yes |
| IA-8 | Identification and Authentication (Non-organizational Users) |  | yes |
| IA-8 | Identification and Authentication (Non-organizational Users) | 1 | yes |
| IA-8 | Identification and Authentication (Non-organizational Users) | 2 | ? |
| IA-8 | Identification and Authentication (Non-organizational Users) | 3 | ? |
| IA-8 | Identification and Authentication (Non-organizational Users) | 4 | ? |
| IR-1 | Incident Response Policy and Procedures |  | no |
| IR-2 | Incident Response Training |  | no |
| IR-3 | Incident Response Testing |  | no |
| IR-3 | Incident Response Testing | 2 | no |
| IR-4 | Incident Handling |  | no |
| IR-4 | Incident Handling | 1 | no |
| IR-5 | Incident Monitoring |  | yes |
| IR-6 | Incident Reporting |  | no |
| IR-6 | Incident Reporting | 1 | no |
| IR-7 | Incident Response Assistance |  | no |
| IR-7 | Incident Response Assistance | 1 | no |
| IR-8 | Incident Response Plan |  | no |
| MA-1 | System Maintenance Policy and Procedures |  | no |
| MA-2 | Controlled Maintenance |  | no |
| MA-3 | Maintenance Tools |  | no |
| MA-3 | Maintenance Tools | 1 | no |
| MA-3 | Maintenance Tools | 2 | no |
| MA-4 | Nonlocal Maintenance |  | no |
| MA-4 | Nonlocal Maintenance | 2 | no |
| MA-5 | Maintenance Personnel |  | no |
| MA-6 | Timely Maintenance |  | no |
| MP-1 | Media Protection Policy and Procedures |  | no |
| MP-2 | Media Access |  | no |
| MP-3 | Media Marking |  | no |
| MP-4 | Media Storage |  | no |
| MP-5 | Media Transport |  | no |
| MP-5 | Media Transport | 4 | no |
| MP-6 | Media Sanitization |  | no |
| MP-7 | Media Use |  | no |
| MP-7 | Media Use | 1 | no |
| PE-1 | Physical and Environmental Protection Policy and Procedures |  | yes |
| PE-2 | Physical Access Authorizations |  | yes |
| PE-3 | Physical Access Control |  | yes |
| PE-4 | Access Control for Transmission Medium |  | yes |
| PE-5 | Access Control for Output Devices |  | yes |
| PE-6 | Monitoring Physical Access |  | yes |
| PE-6 | Monitoring Physical Access | 1 | yes |
| PE-8 | Visitor Access Records |  | yes |
| PE-9 | Power Equipment and Cabling |  | yes |
| PE-10 | Emergency Shutoff |  | yes |
| PE-11 | Emergency Power |  | yes |
| PE-12 | Emergency Lighting |  | yes |
| PE-13 | Fire Protection |  | yes |
| PE-13 | Fire Protection | 3 | yes |
| PE-14 | Temperature and Humidity Controls |  | yes |
| PE-15 | Water Damage Protection |  | yes |
| PE-16 | Delivery and Removal |  | yes |
| PE-17 | Alternate Work Site |  | yes |
| PL-1 | Security Planning Policy and Procedures |  | no |
| PL-2 | System Security Plan |  | no |
| PL-2 | System Security Plan | 3 | no |
| PL-4 | Rules of Behavior |  | yes |
| PL-4 | Rules of Behavior | 1 | no |
| PL-8 | Information Security Architecture |  | no |
| PS-1 | Personnel Security Policy and Procedures |  | no |
| PS-2 | Position Risk Designation |  | no |
| PS-3 | Personnel Screening |  | no |
| PS-4 | Personnel Termination |  | no |
| PS-5 | Personnel Transfer |  | no |
| PS-6 | Access Agreements |  | no |
| PS-7 | Third-party Personnel Security |  | no |
| PS-8 | Personnel Sanctions |  | no |
| RA-1 | Risk Assessment Policy and Procedures |  | no |
| RA-2 | Security Categorization |  | no |
| RA-3 | Risk Assessment |  | no |
| RA-5 | Vulnerability Scanning |  | yes |
| RA-5 | Vulnerability Scanning | 1 | yes |
| RA-5 | Vulnerability Scanning | 2 | yes |
| RA-5 | Vulnerability Scanning | 5 | yes |
| SA-1 | System and Services Acquisition Policy and Procedures |  | no |
| SA-2 | Allocation of Resources |  | no |
| SA-3 | System Development Life Cycle |  | no |
| SA-4 | Acquisition Process |  | no |
| SA-4 | Acquisition Process | 1 | no |
| SA-4 | Acquisition Process | 2 | no |
| SA-4 | Acquisition Process | 9 | yes |
| SA-4 | Acquisition Process | 10 | no |
| SA-5 | Information System Documentation |  | yes |
| SA-8 | Security Engineering Principles |  | no |
| SA-9 | External Information System Services |  | no |
| SA-9 | External Information System Services | 2 | no |
| SA-10 | Developer Configuration Management |  | no |
| SA-11 | Developer Security Testing and Evaluation |  | yes |
| SC-1 | System and Communications Protection Policy and Procedures |  | no |
| SC-2 | Application Partitioning |  | yes |
| SC-4 | Information in Shared Resources |  | yes |
| SC-5 | Denial of Service Protection |  | yes |
| SC-7 | Boundary Protection |  | yes |
| SC-7 | Boundary Protection | 3 | yes |
| SC-7 | Boundary Protection | 4 | yes |
| SC-7 | Boundary Protection | 5 | yes |
| SC-7 | Boundary Protection | 7 | yes |
| SC-8 | Transmission Confidentiality and Integrity |  | yes |
| SC-8 | Transmission Confidentiality and Integrity | 1 | yes |
| SC-10 | Network Disconnect |  | yes |
| SC-12 | Cryptographic Key Establishment and Management |  | yes |
| SC-13 | Cryptographic Protection |  | yes |
| SC-15 | Collaborative Computing Devices |  | no |
| SC-17 | Public Key Infrastructure Certificates |  | yes |
| SC-18 | Mobile Code |  | yes |
| SC-19 | Voice Over Internet Protocol |  | no |
| SC-20 | Secure Name / Address Resolution Service (Authoritative Source) |  | yes |
| SC-21 | Secure Name / Address Resolution Service (Recursive or Caching Resolver) |  | yes |
| SC-22 | Architecture and Provisioning for Name / Address Resolution Service |  | yes |
| SC-23 | Session Authenticity |  | yes |
| SC-28 | Protection of Information at Rest |  | yes |
| SC-39 | Process Isolation |  | yes |
| SI-1 | System and Information Integrity Policy and Procedures |  | no |
| SI-2 | Flaw Remediation |  | yes |
| SI-2 | Flaw Remediation | 2 | yes |
| SI-3 | Malicious Code Protection |  | yes |
| SI-3 | Malicious Code Protection | 1 | yes |
| SI-3 | Malicious Code Protection | 2 | yes |
| SI-4 | Information System Monitoring |  | yes |
| SI-4 | Information System Monitoring | 2 | yes |
| SI-4 | Information System Monitoring | 4 | yes |
| SI-4 | Information System Monitoring | 5 | yes |
| SI-5 | Security Alerts, Advisories, and Directives |  | no |
| SI-7 | Software, Firmware, and Information Integrity |  | yes |
| SI-7 | Software, Firmware, and Information Integrity | 1 | yes |
| SI-7 | Software, Firmware, and Information Integrity | 7 | no |
| SI-8 | Spam Protection |  | yes |
| SI-8 | Spam Protection | 1 | no |
| SI-8 | Spam Protection | 2 | yes |
| SI-10 | Information Input Validation |  | yes |
| SI-11 | Error Handling |  | yes |
| SI-12 | Information Handling and Retention |  | no |
| SI-16 | Memory Protection |  | yes |

**Comment by waldoj** [comment]
I think this is as done as it needs to be to satisfy this task. Of course, a very close reading of each will be required next, but that's a part of the overall compliance process, rather than a discrete task.
