### ISSUE TITLE
Identify which controls can be verified automatically

### ISSUE THREAD

**Issue by waldoj** [ustaxcourt/ato#17]
To support #3, identify which controls are candidates for automation, either in whole or in part. This should be based on the findings of #16.

- [x] Triage all controls — but not enhancements — to determine which appear to be candidates
- [x] Triage all candidates’ enhancements to provide further detail about automation viability
- [x] Create a list of all candidates that can be automated, in whole or in part

**Comment by waldoj** [comment]
Of the 99–106 controls that need to be implemented within / for the EF-CMS, I count 71 controls that are candidates for automation. There are 14 that I'm unclear on. That's between 67% and 86% automatability of the potentially applicable controls

I will provide a list here shortly.

**Comment by waldoj** [comment]
| Control | Automatable 
| ------- | ----------- |
| AC-1 | no |
| AC-2 | no |
| AC-3 | unclear |
| AC-4 | yes |
| AC-5 | yes |
| AC-6 | yes |
| AC-8 | yes |
| AC-9 | yes |
| AC-16 | unclear |
| AC-17 | no |
| AC-18 | no |
| AC-19 | no |
| AC-20 | no |
| AC-23 | yes |
| AC-24 | unclear |
| AC-25 | yes |
| AT-1 | no |
| AT-2 | no |
| AT-3 | no |
| AU-1 | no |
| AU-2 | yes |
| AU-3 | yes |
| AU-4 | yes |
| AU-5 | yes |
| AU-6 | yes |
| AU-8 | yes |
| AU-9 | yes |
| AU-12 | yes |
| AU-13 | yes |
| AU-14 | yes |
| AU-15 | yes |
| AU-16 | no |
| CA-1 | no |
| CA-3 | no |
| CM-1 | no |
| CM-2 | yes |
| CM-3 | unclear |
| CM-5 | yes |
| CM-6 | yes |
| CM-7 | yes |
| CM-8 | yes |
| CM-9 | no |
| CM-11 | no |
| CP-1 | no |
| CP-2 | no |
| CP-6 | yes |
| CP-7 | yes |
| CP-8 | no |
| CP-9 | yes |
| CP-10 | yes |
| CP-11 | yes |
| CP-12 | yes |
| CP-13 | yes |
| IA-1 | no |
| IA-2 | yes |
| IA-3 | no |
| IA-4 | unclear |
| IA-5 | yes |
| IA-7 | yes |
| IA-8 | yes |
| IA-9 | yes |
| IA-10 | yes |
| IA-11 | yes |
| IR-1 | no |
| IR-4 | no |
| IR-5 | yes |
| IR-6 | no |
| IR-8 | no |
| IR-9 | no |
| IR-10 | no |
| MA-1 | no |
| MP-1 | no |
| MP-2 | no |
| MP-4 | no |
| MP-5 | no |
| MP-6 | no |
| MP-7 | no |
| MP-8 | yes |
| PE-1 | yes |
| PE-2 | yes |
| PE-3 | yes |
| PE-4 | no |
| PE-6 | yes |
| PE-9 | yes |
| PE-10 | yes |
| PE-11 | yes |
| PE-12 | yes |
| PE-13 | yes |
| PE-14 | yes |
| PE-15 | yes |
| PE-19 | yes |
| PE-20 | yes |
| PL-1 | no |
| PL-2 | no |
| PL-7 | no |
| PL-8 | no |
| PL-9 | no |
| PS-1 | no |
| PS-2 | no |
| PS-3 | no |
| PS-4 | no |
| PS-7 | no |
| RA-1 | no |
| RA-2 | no |
| RA-3 | no |
| RA-5 | yes |
| RA-6 | yes |
| SA-1 | no |
| SA-2 | no |
| SA-3 | no |
| SA-4 | no |
| SA-8 | no |
| SA-9 | no |
| SA-10 | no |
| SA-11 | yes |
| SA-12 | no |
| SA-13 | unclear |
| SA-14 | no |
| SA-17 | yes |
| SA-18 | yes |
| SA-19 | yes |
| SA-20 | yes |
| SA-21 |  |
| SA-22 | yes |
| SC-1 | no |
| SC-2 | yes |
| SC-3 | yes |
| SC-4 | yes |
| SC-5 | yes |
| SC-6 | yes |
| SC-7 | yes |
| SC-8 | yes |
| SC-11 | yes |
| SC-12 | yes |
| SC-13 | yes |
| SC-15 | no |
| SC-16 | no |
| SC-17 | yes |
| SC-19 | no |
| SC-20 | yes |
| SC-21 | yes |
| SC-22 | yes |
| SC-23 | yes |
| SC-24 | yes |
| SC-25 | yes |
| SC-26 | yes |
| SC-27 | yes |
| SC-28 | yes |
| SC-29 | yes |
| SC-30 | yes |
| SC-31 | yes |
| SC-32 | yes |
| SC-34 | yes |
| SC-35 | no |
| SC-36 | yes |
| SC-37 | yes |
| SC-38 | no |
| SC-39 | yes |
| SC-40 | no |
| SC-41 | no |
| SC-42 | no |
| SC-43 | no |
| SC-44 | unclear |
| SI-1 | no |
| SI-2 | yes |
| SI-3 | yes |
| SI-4 | yes |
| SI-5 | no |
| SI-6 | yes |
| SI-7 | yes |
| SI-10 | yes |
| SI-13 | yes |
| SI-14 | yes |
| SI-15 | yes |
| SI-16 | yes |
| SI-17 | yes |

**Comment by waldoj** [comment]
Note that the automated verification of controls is referred to as "automated checklists" in [NIST 800-70](https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-70r4.pdf), and [SCAP is meant to address this](https://csrc.nist.gov/Projects/Security-Content-Automation-Protocol/SCAP-Releases/SCAP-1-3), as a standard.

**Comment by waldoj** [comment]
There's also the [National Checklist Program](https://nvd.nist.gov/ncp/repository), which indexes vendor-created checklists (which aren't necessarily automated checklists). That includes Ansible playbooks and Puppet modules, albeit very few.

**Comment by softwaretzar** [comment]
There is also the DISA Security Technical Implementation Guides STIGS. You can download the [STIGs](https://public.cyber.mil/stigs/downloads/). The STIGs are in the XCCDF - The Extensible Configuration Checklist Description Format and requires the STIG [viewer](https://public.cyber.mil/stigs/srg-stig-tools/)

STIG that is most relevant is the "Application Security and Development STIG - Ver 4, Rel 10"

**Comment by waldoj** [comment]
I have finished determining which controls can be verified automatically, based on my best judgment resulting from a short review of each control and each required enhancement.

| # | Name | Enhancement | Automatable | Notes |
| --- | ----- | ------------ | --------- | -----|
| AC-1 | Access Control Policy and Procedures |  | no |  |
| AC-2 | Account Management |  | no | There are a bunch of control enhancements that do have an EF-CMS bearing |
| AC-2 | Account Management | 1 | yes |  |
| AC-2 | Account Management | 2 | yes |  |
| AC-2 | Account Management | 3 | no |  |
| AC-2 | Account Management | 4 | yes |  |
| AC-3 | Access Enforcement |  | yes |  |
| AC-4 | Information Flow Enforcement |  | yes |  |
| AC-5 | Separation of Duties |  | no |  |
| AC-6 | Least Privilege |  | no |  |
| AC-6 | Least Privilege | 1 | no | Security functions aren't part of the EF-CMS system |
| AC-6 | Least Privilege | 2 | no |  |
| AC-6 | Least Privilege | 5 | no | There is no root in this architecture |
| AC-6 | Least Privilege | 9 | yes | I have security concerns around automating this |
| AC-6 | Least Privilege | 10 | yes |  |
| AC-7 | Unsuccessful Logon Attempts |  | yes |  |
| AC-8 | System Use Notification |  | yes |  |
| AC-10 | Concurrent Session Control |  | yes | Not part of moderate — custom addition |
| AC-11 | Session Lock |  | yes |  |
| AC-11 | Session Lock | 1 | yes |  |
| AC-12 | Session Termination |  | yes |  |
| AC-14 | Permitted Actions Without Identification or Authentication |  | yes |  |
| AC-17 | Remote Access |  | no |  |
| AC-17 | Remote Access | 1 | ? |  |
| AC-17 | Remote Access | 2 | yes |  |
| AC-17 | Remote Access | 3 | ? | But instead of automating it, maybe just check? |
| AC-17 | Remote Access | 4 | no | It's all remote — it's cloud |
| AC-18 | Wireless Access |  | no |  |
| AC-18 | Wireless Access | 1 | ? | This one is weird |
| AC-19 | Access Control for Mobile Devices |  | no |  |
| AC-19 | Access Control for Mobile Devices | 5 | no |  |
| AC-20 | Use of External Information Systems |  | no |  |
| AC-20 | Use of External Information Systems | 1 | no |  |
| AC-20 | Use of External Information Systems | 2 | no |  |
| AC-21 | Information Sharing |  | ? |  |
| AC-22 | Publicly Accessible Content |  | no |  |
| AT-1 | Security Awareness and Training Policy and Procedures |  | no |  |
| AT-2 | Security Awareness Training |  | no |  |
| AT-2 | Security Awareness Training | 2 | no |  |
| AT-3 | Role-based Security Training |  | no |  |
| AT-4 | Security Training Records |  | no |  |
| AU-1 | Audit and Accountability Policy and Procedures |  | no |  |
| AU-2 | Audit Events |  | yes | Automatable in part |
| AU-2 | Audit Events | 3 | no |  |
| AU-3 | Content of Audit Records |  | yes |  |
| AU-3 | Content of Audit Records | 1 | yes |  |
| AU-4 | Audit Storage Capacity |  | yes |  |
| AU-5 | Response to Audit Processing Failures |  | yes |  |
| AU-6 | Audit Review, Analysis, and Reporting |  | yes | This is mostly manual |
| AU-6 | Audit Review, Analysis, and Reporting | 1 | yes |  |
| AU-6 | Audit Review, Analysis, and Reporting | 3 | no |  |
| AU-7 | Audit Reduction and Report Generation |  | yes |  |
| AU-7 | Audit Reduction and Report Generation | 1 | yes | But instead of automating it, maybe just check? |
| AU-8 | Time Stamps |  | yes |  |
| AU-8 | Time Stamps | 1 | yes |  |
| AU-9 | Protection of Audit Information |  | yes |  |
| AU-9 | Protection of Audit Information | 4 | yes | This can only be somewhat automated, due to the inherent security limitations |
| AU-11 | Audit Record Retention |  | yes |  |
| AU-12 | Audit Generation |  | yes |  |
| CA-1 | Security Assessment and Authorization Policy and Procedures |  | no |  |
| CA-2 | Security Assessments |  | no |  |
| CA-2 | Security Assessments | 1 | no |  |
| CA-3 | System Interconnections |  | ? |  |
| CA-3 | System Interconnections | 5 | yes |  |
| CA-5 | Plan of Action and Milestones |  | no |  |
| CA-6 | Security Authorization |  | no |  |
| CA-7 | Continuous Monitoring |  | yes | Can be automated in part |
| CA-7 | Continuous Monitoring | 1 | no |  |
| CA-9 | Internal System Connections |  | yes | Can be automated in part |
| CM-1 | Configuration Management Policy and Procedures |  | no |  |
| CM-2 | Baseline Configuration |  | yes |  |
| CM-2 | Baseline Configuration | 1 | no |  |
| CM-2 | Baseline Configuration | 3 | yes | But instead of automating it, maybe just check? |
| CM-2 | Baseline Configuration | 7 | no |  |
| CM-3 | Configuration Change Control |  | no |  |
| CM-3 | Configuration Change Control | 2 | no | This is inherent to Agile and DevOps |
| CM-4 | Security Impact Analysis |  | no | Our continuous ATO process helps to address this |
| CM-5 | Access Restrictions for Change |  | yes |  |
| CM-6 | Configuration Settings |  | yes |  |
| CM-7 | Least Functionality |  | yes |  |
| CM-7 | Least Functionality | 1 | no |  |
| CM-7 | Least Functionality | 2 | no | I'm dubious this is applicable |
| CM-7 | Least Functionality | 4 | ? | This isn't applicable |
| CM-8 | Information System Component Inventory |  | yes |  |
| CM-8 | Information System Component Inventory | 1 | yes | Inherent to how we work, not even worth automating |
| CM-8 | Information System Component Inventory | 3 | ? |  |
| CM-8 | Information System Component Inventory | 5 | no |  |
| CM-9 | Configuration Management Plan |  | no |  |
| CM-10 | Software Usage Restrictions |  | yes | We could have a package.json for licensed software |
| CM-11 | User-installed Software |  | no |  |
| CP-1 | Contingency Planning Policy and Procedures |  | no |  |
| CP-2 | Contingency Plan |  | no |  |
| CP-2 | Contingency Plan | 1 | no |  |
| CP-2 | Contingency Plan | 3 | no |  |
| CP-2 | Contingency Plan | 8 | no |  |
| CP-3 | Contingency Training |  | no |  |
| CP-4 | Contingency Plan Testing |  | no |  |
| CP-4 | Contingency Plan Testing | 1 | no |  |
| CP-6 | Alternate Storage Site |  | yes |  |
| CP-6 | Alternate Storage Site | 1 | yes |  |
| CP-6 | Alternate Storage Site | 3 | no |  |
| CP-7 | Alternate Processing Site |  | yes |  |
| CP-7 | Alternate Processing Site | 1 | yes |  |
| CP-7 | Alternate Processing Site | 2 | yes |  |
| CP-7 | Alternate Processing Site | 3 | no | This is covered by GovCloud's FedRAMP certificate, I assume |
| CP-8 | Telecommunications Services |  | no |  |
| CP-8 | Telecommunications Services | 1 | no |  |
| CP-8 | Telecommunications Services | 2 | no |  |
| CP-9 | Information System Backup |  | yes |  |
| CP-9 | Information System Backup | 1 | yes |  |
| CP-10 | Information System Recovery and Reconstitution |  | no |  |
| CP-10 | Information System Recovery and Reconstitution | 2 | yes | This is covered by GovCloud's FedRAMP certificate, I assume |
| IA-1 | Identification and Authentication Policy and Procedures |  | no |  |
| IA-2 | Identification and Authentication (Organizational Users) |  | ? |  |
| IA-2 | Identification and Authentication (Organizational Users) | 1 | yes | But instead of automating it, maybe just check? |
| IA-2 | Identification and Authentication (Organizational Users) | 2 | yes |  |
| IA-2 | Identification and Authentication (Organizational Users) | 3 | yes | Not applicable because no local accounts |
| IA-2 | Identification and Authentication (Organizational Users) | 8 | yes | Didn't another control require the ability to replay user sessions? Aren't they mutually exclusive? |
| IA-2 | Identification and Authentication (Organizational Users) | 11 | no | Inherently not automatable |
| IA-2 | Identification and Authentication (Organizational Users) | 12 | ? |  |
| IA-3 | Device Identification and Authentication |  | no | This isn't needed |
| IA-4 | Identifier Management |  | no |  |
| IA-5 | Authenticator Management |  | ? | This is within Cognito, so not automated as much as punted |
| IA-5 | Authenticator Management | 1 | no | This is within Cognito, so not automated as much as punted. This guidance should not be followed to the letter, because it's out of date |
| IA-5 | Authenticator Management | 2 | no |  |
| IA-5 | Authenticator Management | 3 | no |  |
| IA-5 | Authenticator Management | 11 | no |  |
| IA-6 | Authenticator Feedback |  | no | This is within Cognito, so not automated as much as punted. This guidance should not be followed to the letter, because it's out of date |
| IA-7 | Cryptographic Module Authentication |  | yes |  |
| IA-8 | Identification and Authentication (Non-organizational Users) |  | yes |  |
| IA-8 | Identification and Authentication (Non-organizational Users) | 1 | no | This isn't applicable to the EF-CMS |
| IA-8 | Identification and Authentication (Non-organizational Users) | 2 | ? | Not sure if this is applicable, since no other agencies use this. |
| IA-8 | Identification and Authentication (Non-organizational Users) | 3 | ? | Not sure if this is applicable, since no other agencies use this. |
| IA-8 | Identification and Authentication (Non-organizational Users) | 4 | ? | Not sure if this is applicable, since no other agencies use this. |
| IR-1 | Incident Response Policy and Procedures |  | no |  |
| IR-2 | Incident Response Training |  | no |  |
| IR-3 | Incident Response Testing |  | no |  |
| IR-3 | Incident Response Testing | 2 | no |  |
| IR-4 | Incident Handling |  | no |  |
| IR-4 | Incident Handling | 1 | yes |  |
| IR-5 | Incident Monitoring |  | yes | It's automatable, but there'd be no reason to bother |
| IR-6 | Incident Reporting |  | no | Partially automatable, I guess |
| IR-6 | Incident Reporting | 1 | no | Partially automatable, I guess |
| IR-7 | Incident Response Assistance |  | no |  |
| IR-7 | Incident Response Assistance | 1 | no | Partially automatable, I guess |
| IR-8 | Incident Response Plan |  | no |  |
| MA-1 | System Maintenance Policy and Procedures |  | no |  |
| MA-2 | Controlled Maintenance |  | no |  |
| MA-3 | Maintenance Tools |  | no |  |
| MA-3 | Maintenance Tools | 1 | no |  |
| MA-3 | Maintenance Tools | 2 | no |  |
| MA-4 | Nonlocal Maintenance |  | no | Can't see how this applies to cloud hosting |
| MA-4 | Nonlocal Maintenance | 2 | no |  |
| MA-5 | Maintenance Personnel |  | no |  |
| MA-6 | Timely Maintenance |  | no |  |
| MP-1 | Media Protection Policy and Procedures |  | no |  |
| MP-2 | Media Access |  | no | This isn't applicable to the EF-CMS, except for judges' bulk downloads |
| MP-3 | Media Marking |  | no | This isn't applicable to the EF-CMS, except for judges' bulk downloads |
| MP-4 | Media Storage |  | no | This isn't applicable to the EF-CMS, except for judges' bulk downloads |
| MP-5 | Media Transport |  | no | This isn't applicable to the EF-CMS, except for judges' bulk downloads |
| MP-5 | Media Transport | 4 | no |  |
| MP-6 | Media Sanitization |  | no | This isn't applicable to the EF-CMS, except for judges' bulk downloads |
| MP-7 | Media Use |  | no | This isn't applicable to the EF-CMS, except for judges' bulk downloads |
| MP-7 | Media Use | 1 | no |  |
| PE-1 | Physical and Environmental Protection Policy and Procedures |  | no | This is covered by GovCloud's FedRAMP certificate |
| PE-2 | Physical Access Authorizations |  | no | This is covered by GovCloud's FedRAMP certificate |
| PE-3 | Physical Access Control |  | no | This is covered by GovCloud's FedRAMP certificate |
| PE-4 | Access Control for Transmission Medium |  | no | This is covered by GovCloud's FedRAMP certificate |
| PE-5 | Access Control for Output Devices |  | no | This is covered by GovCloud's FedRAMP certificate |
| PE-6 | Monitoring Physical Access |  | no | This is covered by GovCloud's FedRAMP certificate |
| PE-6 | Monitoring Physical Access | 1 | no | This is covered by GovCloud's FedRAMP certificate |
| PE-8 | Visitor Access Records |  | no | This is covered by GovCloud's FedRAMP certificate |
| PE-9 | Power Equipment and Cabling |  | no | This is covered by GovCloud's FedRAMP certificate |
| PE-10 | Emergency Shutoff |  | no | This is covered by GovCloud's FedRAMP certificate |
| PE-11 | Emergency Power |  | no | This is covered by GovCloud's FedRAMP certificate |
| PE-12 | Emergency Lighting |  | no | This is covered by GovCloud's FedRAMP certificate |
| PE-13 | Fire Protection |  | no | This is covered by GovCloud's FedRAMP certificate |
| PE-13 | Fire Protection | 3 | yes | This is covered by GovCloud's FedRAMP certificate |
| PE-14 | Temperature and Humidity Controls |  | no | This is covered by GovCloud's FedRAMP certificate |
| PE-15 | Water Damage Protection |  | no | This is covered by GovCloud's FedRAMP certificate |
| PE-16 | Delivery and Removal |  | no | This is covered by GovCloud's FedRAMP certificate |
| PE-17 | Alternate Work Site |  | no | This is covered by GovCloud's FedRAMP certificate |
| PL-1 | Security Planning Policy and Procedures |  | no |  |
| PL-2 | System Security Plan |  | no |  |
| PL-2 | System Security Plan | 3 | no |  |
| PL-4 | Rules of Behavior |  | yes | Partially automatable |
| PL-4 | Rules of Behavior | 1 | no |  |
| PL-8 | Information Security Architecture |  | yes | We can draw on EF-CMS IaC to generate portions of this work |
| PS-1 | Personnel Security Policy and Procedures |  | no |  |
| PS-2 | Position Risk Designation |  | no |  |
| PS-3 | Personnel Screening |  | no |  |
| PS-4 | Personnel Termination |  | no |  |
| PS-5 | Personnel Transfer |  | no |  |
| PS-6 | Access Agreements |  | no |  |
| PS-7 | Third-party Personnel Security |  | no |  |
| PS-8 | Personnel Sanctions |  | no |  |
| RA-1 | Risk Assessment Policy and Procedures |  | no |  |
| RA-2 | Security Categorization |  | no |  |
| RA-3 | Risk Assessment |  | no |  |
| RA-5 | Vulnerability Scanning |  | yes |  |
| RA-5 | Vulnerability Scanning | 1 | yes |  |
| RA-5 | Vulnerability Scanning | 2 | yes |  |
| RA-5 | Vulnerability Scanning | 5 | yes | Automating this is unwise, in terms of permissions |
| SA-1 | System and Services Acquisition Policy and Procedures |  | no |  |
| SA-2 | Allocation of Resources |  | no |  |
| SA-3 | System Development Life Cycle |  | no |  |
| SA-4 | Acquisition Process |  | no | This is problematic. Procurements shouldn't work like this. |
| SA-4 | Acquisition Process | 1 | no | This is problematic. Procurements shouldn't work like this. |
| SA-4 | Acquisition Process | 2 | no | This is problematic. Procurements shouldn't work like this. |
| SA-4 | Acquisition Process | 9 | no | This is problematic. Procurements shouldn't work like this. |
| SA-4 | Acquisition Process | 10 | no |  |
| SA-5 | Information System Documentation |  | no | This is basically describing Agile. |
| SA-8 | Security Engineering Principles |  | no |  |
| SA-9 | External Information System Services |  | no |  |
| SA-9 | External Information System Services | 2 | no |  |
| SA-10 | Developer Configuration Management |  | no |  |
| SA-11 | Developer Security Testing and Evaluation |  | yes |  |
| SC-1 | System and Communications Protection Policy and Procedures |  | no |  |
| SC-2 | Application Partitioning |  | yes |  |
| SC-4 | Information in Shared Resources |  | ? | Not sure how automatable this is, but once verified, it won't change |
| SC-5 | Denial of Service Protection |  | yes |  |
| SC-7 | Boundary Protection |  | yes | Not sure how automatable this is, but once verified, it won't change |
| SC-7 | Boundary Protection | 3 | yes | This is a terrible idea |
| SC-7 | Boundary Protection | 4 | ? |  |
| SC-7 | Boundary Protection | 5 | yes |  |
| SC-7 | Boundary Protection | 7 | ? | I don't see how this is applicable |
| SC-8 | Transmission Confidentiality and Integrity |  | ? |  |
| SC-8 | Transmission Confidentiality and Integrity | 1 | yes |  |
| SC-10 | Network Disconnect |  | yes |  |
| SC-12 | Cryptographic Key Establishment and Management |  | ? |  |
| SC-13 | Cryptographic Protection |  | ? |  |
| SC-15 | Collaborative Computing Devices |  | no |  |
| SC-17 | Public Key Infrastructure Certificates |  | yes | But instead of automating it, maybe just check? |
| SC-18 | Mobile Code |  | yes |  |
| SC-19 | Voice Over Internet Protocol |  | no |  |
| SC-20 | Secure Name / Address Resolution Service (Authoritative Source) |  | yes | But instead of automating it, maybe just check? |
| SC-21 | Secure Name / Address Resolution Service (Recursive or Caching Resolver) |  | yes | But instead of automating it, maybe just check? |
| SC-22 | Architecture and Provisioning for Name / Address Resolution Service |  | yes | But instead of automating it, maybe just check? |
| SC-23 | Session Authenticity |  | yes |  |
| SC-28 | Protection of Information at Rest |  | yes |  |
| SC-39 | Process Isolation |  | yes | This may be covered by GovCloud's FedRAMP certificate |
| SI-1 | System and Information Integrity Policy and Procedures |  | no |  |
| SI-2 | Flaw Remediation |  | yes |  |
| SI-2 | Flaw Remediation | 2 | yes |  |
| SI-3 | Malicious Code Protection |  | yes |  |
| SI-3 | Malicious Code Protection | 1 | ? |  |
| SI-3 | Malicious Code Protection | 2 | yes |  |
| SI-4 | Information System Monitoring |  | yes |  |
| SI-4 | Information System Monitoring | 2 | yes | But instead of automating it, maybe just check? |
| SI-4 | Information System Monitoring | 4 | yes | But instead of automating it, maybe just check? |
| SI-4 | Information System Monitoring | 5 | yes | But instead of automating it, maybe just check? |
| SI-5 | Security Alerts, Advisories, and Directives |  | no |  |
| SI-7 | Software, Firmware, and Information Integrity |  | yes |  |
| SI-7 | Software, Firmware, and Information Integrity | 1 | yes |  |
| SI-7 | Software, Firmware, and Information Integrity | 7 | no |  |
| SI-8 | Spam Protection |  | yes |  |
| SI-8 | Spam Protection | 1 | no |  |
| SI-8 | Spam Protection | 2 | yes |  |
| SI-10 | Information Input Validation |  | yes |  |
| SI-11 | Error Handling |  | no |  |
| SI-12 | Information Handling and Retention |  | no |  |
| SI-16 | Memory Protection |  | yes | |

**Comment by waldoj** [comment]
The above list implicitly satisfies the third requirement of this issue — "create a list of all candidates that can be automated."

92 of 262 (or 36%) can be automated. But that's 92 of _EF-CMS-related_ 144 controls and enhancements, which is to say that 64% can be automated. Another 17 are covered by Cognito's FedRAMP status. That leaves the EF-CMS with no more than 35 controls that will require manual verification (and a few of those controls really aren't applicable and should be struck).
